# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hangMan495' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hangMan495

  target 'hangMan495Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'hangMan495UITests' do
    inherit! :search_paths
    # Pods for testing
  end
  #Pods for hangman495
   pod 'Firebase/Core'
   pod 'Firebase/Auth'
end
